name: "Run Examples"

on:
  push:
  pull_request:
  workflow_dispatch:
    inputs:
      pyglotaran_branch:
        description: "pyglotaran branch/tag to run the examples against"
        required: true
        default: "main"
      pyglotaran_examples_branch:
        description: "pyglotaran-examples branch/tag to use"
        required: true
        default: "main"
      install_extras:
        description: "Whether or not to install pyglotaran_extras"
        required: true
        default: "true"

jobs:
  run-examples:
    name: "Run Example: "
    runs-on: ubuntu-latest
    strategy:
      matrix:
        example_name:
          [
            quick-start,
            fluorescence,
            transient-absorption,
            transient-absorption-two-datasets,
            spectral-constraints,
            spectral-guidance,
            two-datasets,
            sim-3d-disp,
            sim-3d-nodisp,
            sim-3d-weight,
            sim-6d-disp,
          ]
    steps:
      - uses: actions/checkout@v2
        with:
          repository: "glotaran/pyglotaran"
          # If not provided (push and pull_request event) it uses the default branch
          ref: ${{ github.event.inputs.pyglotaran_branch }}
      - name: Set up Python 3.8
        uses: actions/setup-python@v3
        with:
          python-version: 3.8
      - name: Install pyglotaran
        run: |
          pip install wheel
          pip install .
      - name: Cloning pyglotaran-examples
        if: ${{ github.event.inputs.pyglotaran_examples_branch }} == ""
        uses: actions/checkout@v2
        with:
          path: pyglotaran-examples
      - id: example-run
        uses: ./pyglotaran-examples
        with:
          example_name: ${{ matrix.example_name }}
          examples_branch: ${{ github.event.inputs.pyglotaran_examples_branch }}
          install_extras: ${{ github.event.inputs.install_extras }}
      - name: Upload Example Plots Artifact
        uses: actions/upload-artifact@v2
        with:
          name: example-results
          path: ${{ steps.example-run.outputs.plots-path }}
